// Package jsonltest generates deterministic JSONL session corpora and
// instrumented filesystems for tests of JSONL-backed conversation sources.
// Nothing under internal/vendors imports it outside a test, so there is no
// cycle. Every fatal-ing helper wraps an error-returning core, because only
// the core has a failure a test can observe.
package jsonltest

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math/rand/v2"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"
)

// Shape selects the vendor layout a corpus imitates.
type Shape int

const (
	// ShapeUnset is the zero value; Shape has no default.
	ShapeUnset Shape = iota
	// ShapeClaude imitates ~/.claude/projects/<project>/*.jsonl.
	ShapeClaude
	// ShapePi imitates ~/.pi/agent/sessions/<project>/*.jsonl.
	ShapePi
)

func (s Shape) String() string {
	switch s {
	case ShapeClaude:
		return "claude"
	case ShapePi:
		return "pi"
	case ShapeUnset:
		return "unset"
	}
	return fmt.Sprintf("Shape(%d)", int(s))
}

// Kind labels one generated session file. Every kind but KindOrdinary is an
// awkward case some invariant depends on.
type Kind int

const (
	KindOrdinary Kind = iota
	KindLongSession
	KindQuotedRoleMarker
	KindSidechainFile
	KindSidechainLines
	KindToolResult
	// KindToolResultFirstUser opens with a tool-result-only user line, so the
	// count and the preview disagree about it.
	KindToolResultFirstUser
	KindNoIdentity
	KindEmptyFile
	KindNoTrailingNewline
	KindLateIdentity
	KindTwoIdentities
)

func (k Kind) String() string {
	names := map[Kind]string{
		KindOrdinary:            "ordinary",
		KindLongSession:         "long-session",
		KindQuotedRoleMarker:    "quoted-role-marker",
		KindSidechainFile:       "sidechain-file",
		KindSidechainLines:      "sidechain-lines",
		KindToolResult:          "tool-result",
		KindToolResultFirstUser: "tool-result-first-user",
		KindNoIdentity:          "no-identity",
		KindEmptyFile:           "empty-file",
		KindNoTrailingNewline:   "no-trailing-newline",
		KindLateIdentity:        "late-identity",
		KindTwoIdentities:       "two-identities",
	}
	if n, ok := names[k]; ok {
		return n
	}
	return fmt.Sprintf("Kind(%d)", int(k))
}

// RequiredKinds is every awkward fixture, in the order the generator assigns.
var RequiredKinds = []Kind{
	KindLongSession,
	KindQuotedRoleMarker,
	KindSidechainFile,
	KindSidechainLines,
	KindToolResult,
	KindToolResultFirstUser,
	KindNoIdentity,
	KindEmptyFile,
	KindNoTrailingNewline,
	KindLateIdentity,
	KindTwoIdentities,
}

const (
	DefaultSessions = 64
	// DefaultLinesPerSession outgrows any per-file head a discovery might read.
	DefaultLinesPerSession = 250
	DefaultSeed            = 1
	// corpusProjects is how many project directories a corpus spreads over.
	corpusProjects = 4
	// corpusEpoch anchors generated timestamps well in the past.
	corpusEpoch = 1_700_000_000
)

// MinSessions yields every required kind plus one ordinary session.
var MinSessions = len(RequiredKinds) + 1

// CorpusOptions describes a corpus. A zero LinesPerSession or Seed takes the
// package default; a zero Sessions means an empty corpus.
type CorpusOptions struct {
	Shape           Shape
	Sessions        int
	LinesPerSession int
	Seed            int64
}

// SessionFact is the oracle for one generated file, asserted against instead
// of a number written into a document. A file with no identity has an empty
// SessionID.
type SessionFact struct {
	Path          string
	Kind          Kind
	SessionID     string
	Cwd           string
	Created       time.Time
	Model         string
	FirstUserText string
	Messages      int
}

// Corpus holds Files and Sessions in walk order, index-aligned. Only the
// fixed-width generated names make that a lexical path sort (R2-02).
type Corpus struct {
	Root     string
	Files    []string
	Sessions []SessionFact
}

// Lines reads every non-empty line in walk order, so a conformance run sees
// generated bytes and not lines written to pass.
func (c Corpus) Lines() ([][]byte, error) {
	out := [][]byte{}
	for _, p := range c.Files {
		b, err := os.ReadFile(p)
		if err != nil {
			return nil, fmt.Errorf("jsonltest: read session %q: %w", p, err)
		}
		for line := range bytes.SplitSeq(b, []byte("\n")) {
			if line = bytes.TrimSpace(line); len(line) > 0 {
				out = append(out, line)
			}
		}
	}
	return out, nil
}

func (c Corpus) WithKind(k Kind) []SessionFact {
	out := []SessionFact{}
	for _, f := range c.Sessions {
		if f.Kind == k {
			out = append(out, f)
		}
	}
	return out
}

func WriteCorpus(tb testing.TB, root string, opts CorpusOptions) Corpus {
	tb.Helper()
	c, err := WriteCorpusErr(root, opts)
	if err != nil {
		tb.Fatalf("jsonltest.WriteCorpus(%q): %v", root, err)
	}
	return c
}

// WriteCorpusErr is deterministic for a given seed: two calls produce
// byte-identical files and identical facts.
func WriteCorpusErr(root string, opts CorpusOptions) (Corpus, error) {
	if opts.Shape != ShapeClaude && opts.Shape != ShapePi {
		return Corpus{}, fmt.Errorf("jsonltest: CorpusOptions.Shape must be ShapeClaude or ShapePi, got %v", opts.Shape)
	}
	if opts.LinesPerSession <= 0 {
		opts.LinesPerSession = DefaultLinesPerSession
	}
	if opts.Seed == 0 {
		opts.Seed = DefaultSeed
	}
	if err := os.MkdirAll(root, 0o755); err != nil {
		return Corpus{}, fmt.Errorf("jsonltest: create corpus root %q: %w", root, err)
	}
	c := Corpus{Root: root}
	for i := range opts.Sessions {
		kind := KindOrdinary
		if i < len(RequiredKinds) {
			kind = RequiredKinds[i]
		}
		dir := filepath.Join(root, fmt.Sprintf("proj-%02d", i%corpusProjects))
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return Corpus{}, fmt.Errorf("jsonltest: create project dir %q: %w", dir, err)
		}
		path := filepath.Join(dir, fmt.Sprintf("session-%04d.jsonl", i))
		lines, err := buildSession(opts, i, kind)
		if err != nil {
			return Corpus{}, err
		}
		if err := writeLines(path, lines, kind != KindNoTrailingNewline); err != nil {
			return Corpus{}, err
		}
		fact := factsFrom(opts.Shape, lines)
		fact.Path, fact.Kind = path, kind
		c.Sessions = append(c.Sessions, fact)
	}
	// Fixed-width names make a lexical path sort equal the walk order.
	slices.SortFunc(c.Sessions, func(a, b SessionFact) int { return strings.Compare(a.Path, b.Path) })
	c.Files = make([]string, 0, len(c.Sessions))
	for _, f := range c.Sessions {
		c.Files = append(c.Files, f.Path)
	}
	return c, nil
}

func writeLines(path string, lines [][]byte, trailingNewline bool) error {
	buf := strings.Builder{}
	for i, line := range lines {
		buf.Write(line)
		if i < len(lines)-1 || trailingNewline {
			buf.WriteByte('\n')
		}
	}
	if err := os.WriteFile(path, []byte(buf.String()), 0o644); err != nil {
		return fmt.Errorf("jsonltest: write session %q: %w", path, err)
	}
	return nil
}

func buildSession(opts CorpusOptions, i int, kind Kind) ([][]byte, error) {
	g := generator{
		shape: opts.Shape,
		sid:   fmt.Sprintf("%v-session-%04d", opts.Shape, i),
		alt:   fmt.Sprintf("%v-session-%04d-b", opts.Shape, i),
		cwd:   fmt.Sprintf("/home/fixture/proj-%02d", i%corpusProjects),
		model: fmt.Sprintf("fixture-model-%d", i%3),
		base:  time.Unix(corpusEpoch+opts.Seed*3600, 0).UTC().Add(time.Duration(i) * time.Hour),
		rng:   rand.New(rand.NewPCG(uint64(opts.Seed), uint64(i)+1)),
	}
	n := opts.LinesPerSession
	if kind == KindEmptyFile {
		return nil, nil
	}
	if kind == KindLongSession {
		n *= 2
	}
	envs := g.session(kind, n)
	out := make([][]byte, 0, len(envs))
	for _, env := range envs {
		b, err := json.Marshal(env)
		if err != nil {
			return nil, fmt.Errorf("jsonltest: marshal fixture line: %w", err)
		}
		out = append(out, b)
	}
	return out, nil
}

type generator struct {
	shape Shape
	sid   string
	alt   string
	cwd   string
	model string
	base  time.Time
	rng   *rand.Rand
}

var fixtureWords = []string{
	"alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf",
	"hotel", "india", "juliet", "kilo", "lima", "mike", "november",
}

func (g *generator) text(prefix string, j int) string {
	words := make([]string, 0, 6)
	for range 4 + g.rng.IntN(3) {
		words = append(words, fixtureWords[g.rng.IntN(len(fixtureWords))])
	}
	return fmt.Sprintf("%s %d %s", prefix, j, strings.Join(words, " "))
}

// quotedRoleMarker makes a substring-matching prefilter or counter over-count.
const quotedRoleMarker = `see the log line {"type":"user","message":{"role":"user"}} above`

func (g *generator) ts(j int) time.Time { return g.base.Add(time.Duration(j) * time.Second) }

func (g *generator) session(kind Kind, n int) []map[string]any {
	if g.shape == ShapePi {
		return g.piSession(kind, n)
	}
	return g.claudeSession(kind, n)
}

func (g *generator) claudeSession(kind Kind, n int) []map[string]any {
	out := make([]map[string]any, 0, n)
	for j := range n {
		sid := g.sid
		switch {
		case kind == KindNoIdentity:
			sid = ""
		case kind == KindTwoIdentities && j >= n/2:
			sid = g.alt
		case kind == KindLateIdentity && j == 0:
			out = append(out, map[string]any{
				"type": "system", "subtype": "init",
				"cwd": g.cwd, "timestamp": g.ts(j).Format(time.RFC3339),
			})
			continue
		}
		var env map[string]any
		switch {
		case kind == KindToolResultFirstUser && j == 0:
			env = g.claudeToolResultLine(sid, j, false)
		case kind == KindToolResult && j == 2:
			env = g.claudeToolResultLine(sid, j, true)
		case kind == KindQuotedRoleMarker && j == 1:
			env = g.claudeLine(sid, j, "assistant", quotedRoleMarker)
		case j%2 == 0:
			env = g.claudeLine(sid, j, "user", g.text("user turn", j))
		default:
			env = g.claudeLine(sid, j, "assistant", g.text("assistant turn", j))
		}
		if kind == KindSidechainFile || (kind == KindSidechainLines && j%5 == 3) {
			env["isSidechain"] = true
		}
		out = append(out, env)
	}
	return out
}

func (g *generator) claudeLine(sid string, j int, role, text string) map[string]any {
	msg := map[string]any{
		"role":    role,
		"content": []any{map[string]any{"type": "text", "text": text}},
	}
	if role == "assistant" {
		msg["model"] = g.model
	}
	return g.claudeEnvelope(sid, j, role, msg)
}

func (g *generator) claudeToolResultLine(sid string, j int, withText bool) map[string]any {
	blocks := []any{map[string]any{
		"type":        "tool_result",
		"tool_use_id": fmt.Sprintf("tool-%04d", j),
		"content":     fmt.Sprintf("tool-result output %d", j),
	}}
	if withText {
		blocks = append(blocks, map[string]any{"type": "text", "text": g.text("user turn", j)})
	}
	return g.claudeEnvelope(sid, j, "user", map[string]any{"role": "user", "content": blocks})
}

func (g *generator) claudeEnvelope(sid string, j int, typ string, msg map[string]any) map[string]any {
	env := map[string]any{
		"type":      typ,
		"cwd":       g.cwd,
		"timestamp": g.ts(j).Format(time.RFC3339),
		"message":   msg,
		"uuid":      fmt.Sprintf("uuid-%04d", j),
	}
	if sid != "" {
		env["sessionId"] = sid
	}
	return env
}

func (g *generator) piSession(kind Kind, n int) []map[string]any {
	out := make([]map[string]any, 0, n)
	for j := range n {
		switch {
		case kind == KindLateIdentity && j == 0:
			out = append(out, map[string]any{
				"type": "model_change", "model": g.model,
				"timestamp": g.ts(j).Format(time.RFC3339Nano),
			})
			continue
		case kind == KindLateIdentity && j == 1,
			kind != KindNoIdentity && kind != KindLateIdentity && j == 0:
			out = append(out, g.piSessionLine(g.sid, j))
			continue
		case kind == KindTwoIdentities && j == n/2:
			out = append(out, g.piSessionLine(g.alt, j))
			continue
		}
		var env map[string]any
		switch {
		case kind == KindToolResultFirstUser && j == 1:
			env = g.piMessage(g.piEmptyUser(j))
		case kind == KindToolResult && j == 3:
			env = g.piMessage(g.piToolResult(j))
		case kind == KindQuotedRoleMarker && j == 2:
			env = g.piMessage(g.piTextMessage("assistant", quotedRoleMarker))
		case j%2 == 1:
			env = g.piMessage(g.piTextMessage("user", g.text("user turn", j)))
		default:
			env = g.piMessage(g.piTextMessage("assistant", g.text("assistant turn", j)))
		}
		if kind == KindSidechainFile || (kind == KindSidechainLines && j%5 == 3) {
			env["isSidechain"] = true
		}
		out = append(out, env)
	}
	return out
}

func (g *generator) piSessionLine(sid string, j int) map[string]any {
	return map[string]any{
		"type": "session", "id": sid, "cwd": g.cwd,
		"timestamp": g.ts(j).Format(time.RFC3339Nano),
	}
}

func (g *generator) piMessage(msg map[string]any) map[string]any {
	return map[string]any{"type": "message", "message": msg}
}

func (g *generator) piTextMessage(role, text string) map[string]any {
	msg := map[string]any{
		"role":    role,
		"content": []any{map[string]any{"type": "text", "text": text}},
	}
	if role == "assistant" {
		msg["model"] = g.model
	}
	return msg
}

func (g *generator) piEmptyUser(j int) map[string]any {
	return map[string]any{
		"role": "user",
		"content": []any{map[string]any{
			"type": "tool_result", "content": fmt.Sprintf("tool-result output %d", j),
		}},
	}
}

func (g *generator) piToolResult(j int) map[string]any {
	return map[string]any{
		"role":       "toolResult",
		"toolCallId": fmt.Sprintf("tool-%04d", j),
		"content":    []any{map[string]any{"type": "text", "text": fmt.Sprintf("tool-result output %d", j)}},
	}
}

func factsFrom(shape Shape, lines [][]byte) SessionFact {
	fact := SessionFact{}
	for _, line := range lines {
		var env map[string]any
		if err := json.Unmarshal(line, &env); err != nil {
			continue
		}
		if shape == ShapePi {
			piFact(env, &fact)
			continue
		}
		claudeFact(env, &fact)
	}
	return fact
}

func claudeFact(env map[string]any, fact *SessionFact) {
	if sc, _ := env["isSidechain"].(bool); sc {
		return
	}
	if fact.SessionID == "" {
		fact.SessionID, _ = env["sessionId"].(string)
	}
	if fact.Cwd == "" {
		fact.Cwd, _ = env["cwd"].(string)
	}
	if fact.Created.IsZero() {
		if ts, _ := env["timestamp"].(string); ts != "" {
			if parsed, err := time.Parse(time.RFC3339, ts); err == nil {
				fact.Created = parsed
			}
		}
	}
	msg, _ := env["message"].(map[string]any)
	switch typ, _ := env["type"].(string); typ {
	case "user":
		fact.Messages++
		if fact.FirstUserText == "" && msg != nil {
			fact.FirstUserText = textContent(msg["content"])
		}
	case "assistant":
		fact.Messages++
		if fact.Model == "" && msg != nil {
			fact.Model, _ = msg["model"].(string)
		}
	}
}

func piFact(env map[string]any, fact *SessionFact) {
	switch typ, _ := env["type"].(string); typ {
	case "session":
		if fact.SessionID == "" {
			fact.SessionID, _ = env["id"].(string)
		}
		if fact.Cwd == "" {
			fact.Cwd, _ = env["cwd"].(string)
		}
		if fact.Created.IsZero() {
			if ts, _ := env["timestamp"].(string); ts != "" {
				if parsed, err := time.Parse(time.RFC3339Nano, ts); err == nil {
					fact.Created = parsed
				}
			}
		}
	case "message":
		msg, _ := env["message"].(map[string]any)
		if msg == nil {
			return
		}
		switch role, _ := msg["role"].(string); role {
		case "user":
			fact.Messages++
			if fact.FirstUserText == "" {
				fact.FirstUserText = textContent(msg["content"])
			}
		case "assistant":
			fact.Messages++
			if fact.Model == "" {
				fact.Model, _ = msg["model"].(string)
			}
		case "toolResult":
			fact.Messages++
		}
	}
}

// textContent deliberately clones vendors.TextBlocksContent: an oracle that
// shares code with the layer it fixtures agrees with it by construction.
func textContent(content any) string {
	if s, ok := content.(string); ok {
		return s
	}
	arr, ok := content.([]any)
	if !ok {
		return ""
	}
	texts := make([]string, 0, len(arr))
	for _, v := range arr {
		m, ok := v.(map[string]any)
		if !ok {
			continue
		}
		if typ, _ := m["type"].(string); typ != "text" {
			continue
		}
		if s, _ := m["text"].(string); s != "" {
			texts = append(texts, s)
		}
	}
	return strings.Join(texts, "\n")
}
