name: Simple Go Pipeline - release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  call-workflow:
    uses: baalimago/simple-go-pipeline/.github/workflows/release.yml@0f3e945a5090f3b1bc4dfa5bf8a19db616c0a992
    with:
      project-name: clai
      branch: main
      version-var: "github.com/baalimago/clai/internal.BuildVersion"
