name: Simple Go Pipeline - validate

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  call-workflow:
    uses: baalimago/simple-go-pipeline/.github/workflows/validate.yml@4db15db8a791280dfac87dfc23a7f6464ad86e4d
    with:
      go-version: "1.26"
      staticcheck-version: "latest"
      gofumpt-version: latest
